apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: fsx.openzfs.csi.aws.com
    volumeHandle: "fs-094fd29d32641fa10"
    volumeAttributes:
      DNSName: "fs-094fd29d32641fa10.fsx.us-east-1.amazonaws.com"
      ResourceType: "filesystem"
